version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      # Application settings
      - APP_PORT=8001
      
      # Valkey/Redis settings
      - VALKEY_HOST=${VALKEY_HOST}
      - VALKEY_PORT=${VALKEY_PORT}
      - VALKEY_USE_TLS=${VALKEY_USE_TLS}
      
      # AWS settings
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      
      # OpenAI settings
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload

  worker:
    build: .
    environment:
      # Valkey/Redis settings
      - VALKEY_HOST=${VALKEY_HOST}
      - VALKEY_PORT=${VALKEY_PORT}
      - VALKEY_USE_TLS=${VALKEY_USE_TLS}
      
      # AWS settings
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      
      # OpenAI settings
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: celery -A celery_app worker --loglevel=info --pool=solo 