version: '3.8'

services:
  web:
    build: .
    image: dev-orbit-pem_web  # Add this line for predictable tagging
    ports:
      - "8001:8001"
    environment:
      - APP_PORT=8001
      - VALKEY_HOST=${VALKEY_HOST}
      - VALKEY_PORT=${VALKEY_PORT}
      - VALKEY_USE_TLS=${VALKEY_USE_TLS}
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload

  worker:
    build: .
    image: dev-orbit-pem_worker  # Add this line if you want to push this image too
    environment:
      - VALKEY_HOST=${VALKEY_HOST}
      - VALKEY_PORT=${VALKEY_PORT}
      - VALKEY_USE_TLS=${VALKEY_USE_TLS}
      - AWS_REGION=${AWS_REGION:-ap-south-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: celery -A celery_app worker --loglevel=info --pool=solo
